name: Publish to Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g @vscode/vsce
      - name: Package
        run: vsce package --no-dependencies --out moyu-sudoku.vsix
      - name: Publish
        run: vsce publish --packagePath moyu-sudoku.vsix -p "${{ secrets.VSCE_PAT }}"
      - name: Update release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload release moyu-sudoku.vsix --clobber
